(function () {
  function buildAzEmbed(slug) {
    return "https://azgames.io/" + slug + ".embed";
  }

  const games = [
    {
      slug: "trap-the-cat",
      title: "Trap the Cat",
      category: "Logic & Drawing",
      sourceUrl: "https://azgames.io/trap-the-cat",
      playerUrl: "https://azgames.io/trap-the-cat.embed",
      summary: "Block the cat's escape route on a hex board before it reaches the edge.",
      intro: "Trap the Cat is a quick logic puzzle built around spatial planning. Each tap closes one route, so the puzzle is really about reading the board two or three steps ahead.",
      bestFor: "Players who like route blocking and short-turn strategy puzzles.",
      session: "2 to 6 minutes",
      difficulty: "Easy to medium",
      tags: ["logic", "grid", "strategy"],
      featured: true
    },
    {
      slug: "golf-puzzle",
      title: "Golf Puzzle",
      category: "Logic & Drawing",
      sourceUrl: "https://gamea.azgame.io/golf-puzzle/",
      playerUrl: buildAzEmbed("golf-puzzle"),
      summary: "Plan angles and simple movement paths to guide the ball into place.",
      intro: "Golf Puzzle mixes clean level design with a compact ruleset. It fits PuzzleGames well because players can understand the goal immediately and still feel challenged by the execution.",
      bestFor: "Casual puzzle players who like short levels and tidy problem solving.",
      session: "3 to 8 minutes",
      difficulty: "Easy to medium",
      tags: ["golf", "logic", "trajectory"],
      featured: true
    },
    {
      slug: "brain-lines",
      title: "Brain Lines",
      category: "Logic & Drawing",
      sourceUrl: "https://gamea.azgame.io/brain-lines/",
      playerUrl: buildAzEmbed("brain-lines"),
      summary: "Draw paths and supports to guide moving objects with simple physics.",
      intro: "Brain Lines is the kind of drawing puzzle that works well on both desktop and mobile. The rules stay simple while the level solutions become more creative over time.",
      bestFor: "Players who enjoy physics puzzles and line-drawing mechanics.",
      session: "4 to 10 minutes",
      difficulty: "Medium",
      tags: ["drawing", "physics", "brain teaser"],
      featured: true
    },
    {
      slug: "sugar-sugar",
      title: "Sugar Sugar",
      category: "Logic & Drawing",
      sourceUrl: "https://azgames.io/sugar-sugar",
      playerUrl: "https://azgames.io/sugar-sugar.embed",
      summary: "Draw lines carefully to route falling sugar into waiting cups.",
      intro: "Sugar Sugar is a slower and more thoughtful drawing puzzle. It rewards clean line placement and patience rather than fast reactions.",
      bestFor: "Players who like calm, methodical puzzle solving.",
      session: "4 to 12 minutes",
      difficulty: "Medium",
      tags: ["drawing", "physics", "calm"],
      featured: false
    },
    {
      slug: "dark-loop",
      title: "Dark Loop",
      category: "Logic & Drawing",
      sourceUrl: "https://gamea.azgame.io/dark-loop/",
      playerUrl: buildAzEmbed("dark-loop"),
      summary: "Solve looping stages where the answer often depends on breaking expectations.",
      intro: "Dark Loop leans into puzzle twists and repeat-room logic. It stands out because the challenge is not only what you see on screen, but how the stage rules are interpreted.",
      bestFor: "Players who want clever puzzle-room ideas instead of raw speed.",
      session: "5 to 12 minutes",
      difficulty: "Medium to hard",
      tags: ["logic", "escape", "twist"],
      featured: false
    },
    {
      slug: "thief-puzzle",
      title: "Thief Puzzle",
      category: "Logic & Drawing",
      sourceUrl: "https://www.crazygames.com/game/thief-puzzle",
      playerUrl: null,
      summary: "Extend a sneaky hand around obstacles and grab the target item safely.",
      intro: "Thief Puzzle is ideal for players who enjoy visual logic stages with a bit of humor. It fits the site because each level is immediately readable and shareable.",
      bestFor: "Mobile users and short-session puzzle fans.",
      session: "2 to 7 minutes",
      difficulty: "Easy to medium",
      tags: ["casual", "logic", "path"],
      featured: true
    },
    {
      slug: "doodle-road",
      title: "Doodle Road",
      category: "Logic & Drawing",
      sourceUrl: "https://www.crazygames.com/game/doodle-road",
      playerUrl: null,
      summary: "Sketch a road, then test whether the route actually carries the vehicle through.",
      intro: "Doodle Road blends drawing and trial-and-error in a compact format. It makes a strong support title for a puzzle catalog because the core hook is easy to explain in one sentence.",
      bestFor: "Players who like creative inputs and quick retries.",
      session: "3 to 8 minutes",
      difficulty: "Medium",
      tags: ["drawing", "route", "casual"],
      featured: false
    },
    {
      slug: "arrow-escape-puzzle",
      title: "Arrow Escape Puzzle",
      category: "Logic & Drawing",
      sourceUrl: "https://www.crazygames.com/game/arrow-escape-puzzle",
      playerUrl: null,
      summary: "Redirect arrows and movement routes until each escape path makes sense.",
      intro: "Arrow Escape Puzzle fits the site's logic-focused side. It gives you a clear board state, a small set of mechanics, and enough room for experimentation.",
      bestFor: "Players who enjoy route planning and compact brain teasers.",
      session: "3 to 9 minutes",
      difficulty: "Medium",
      tags: ["arrows", "logic", "route"],
      featured: false
    },
    {
      slug: "merge-infinity",
      title: "Merge Infinity",
      category: "2048 & Merge",
      sourceUrl: "https://gamea.azgame.io/merge-infinity/",
      playerUrl: buildAzEmbed("merge-infinity"),
      summary: "Keep combining matching pieces to extend the board and preserve momentum.",
      intro: "Merge Infinity is good evergreen content because players already understand the merge concept, but still want new board variations and longer runs.",
      bestFor: "Fans of relaxing but sticky merge loops.",
      session: "5 to 15 minutes",
      difficulty: "Easy to medium",
      tags: ["merge", "numbers", "board"],
      featured: false
    },
    {
      slug: "2048",
      title: "2048",
      category: "2048 & Merge",
      sourceUrl: "https://azgames.io/2048",
      playerUrl: "https://azgames.io/2048.embed",
      summary: "Slide numbered tiles together and build toward the classic 2048 goal.",
      intro: "2048 is one of the most recognizable browser puzzle formats. It gives the homepage a familiar anchor and helps capture broad search demand around number puzzle games.",
      bestFor: "Anyone who wants a quick number puzzle with simple controls.",
      session: "3 to 12 minutes",
      difficulty: "Easy to medium",
      tags: ["2048", "numbers", "classic"],
      featured: true
    },
    {
      slug: "suika-game",
      title: "Suika Game",
      category: "2048 & Merge",
      sourceUrl: "https://azgames.io/suika-game",
      playerUrl: "https://azgames.io/suika-game.embed",
      summary: "Merge matching fruit into bigger pieces before the container overflows.",
      intro: "Suika Game gives the catalog a modern merge hit with strong mobile appeal. The rules are simple, but the placement decisions stay interesting for longer sessions.",
      bestFor: "Players who like physics-heavy merge games.",
      session: "5 to 15 minutes",
      difficulty: "Medium",
      tags: ["merge", "fruit", "physics"],
      featured: true
    },
    {
      slug: "merge-brainrot",
      title: "Merge Brainrot",
      category: "2048 & Merge",
      sourceUrl: "https://game.azgame.io/merge-brainrot/",
      playerUrl: buildAzEmbed("merge-brainrot"),
      summary: "Chain absurd merge upgrades in a meme-styled progression loop.",
      intro: "Merge Brainrot is less about elegant minimalism and more about novelty. It adds tonal variety to the catalog without leaving the familiar merge framework.",
      bestFor: "Players who want lightweight humor mixed with merge mechanics.",
      session: "4 to 12 minutes",
      difficulty: "Easy",
      tags: ["merge", "meme", "casual"],
      featured: false
    },
    {
      slug: "2048-rogue",
      title: "2048 Rogue",
      category: "2048 & Merge",
      sourceUrl: "https://gamea.azgame.io/2048-rogue/",
      playerUrl: buildAzEmbed("2048-rogue"),
      summary: "A 2048 variant that adds pressure, progression, and longer-run decisions.",
      intro: "2048 Rogue is useful for long-tail SEO because it targets players who already know the base 2048 formula and want a twist rather than a clone.",
      bestFor: "Returning 2048 players looking for a more layered loop.",
      session: "6 to 18 minutes",
      difficulty: "Medium",
      tags: ["2048", "roguelike", "strategy"],
      featured: false
    },
    {
      slug: "2048-italian-brainrot",
      title: "2048 Italian Brainrot",
      category: "2048 & Merge",
      sourceUrl: "https://game.azgame.io/2048-italian-brainrot/",
      playerUrl: buildAzEmbed("2048-italian-brainrot"),
      summary: "A novelty 2048 remix with themed tile progression and joke appeal.",
      intro: "This page works best as a trend-friendly side entry in the catalog. The core draw is still the familiar 2048 mechanic, but the presentation gives it a fresh click hook.",
      bestFor: "Players who like meme variants of familiar puzzle systems.",
      session: "3 to 10 minutes",
      difficulty: "Easy",
      tags: ["2048", "variant", "meme"],
      featured: false
    },
    {
      slug: "2048-drop",
      title: "2048 Drop",
      category: "2048 & Merge",
      sourceUrl: "https://game.azgame.io/2048-drop/",
      playerUrl: buildAzEmbed("2048-drop"),
      summary: "Drop numbered tiles from above and merge them before the stack gets too tall.",
      intro: "2048 Drop adds gravity and stack management to the base number-merge loop. That makes it a useful bridge between 2048 pages and physics-style puzzle content.",
      bestFor: "Players who like number games with falling-piece pressure.",
      session: "5 to 14 minutes",
      difficulty: "Medium",
      tags: ["2048", "drop", "numbers"],
      featured: false
    },
    {
      slug: "trimerge",
      title: "Trimerge",
      category: "2048 & Merge",
      sourceUrl: "https://game.azgame.io/trimerge/",
      playerUrl: buildAzEmbed("trimerge"),
      summary: "Merge triples instead of pairs and manage tighter board spacing.",
      intro: "Trimerge is a good catalog differentiator because it changes the merge rule just enough to feel fresh without becoming hard to explain.",
      bestFor: "Players who already like merge games and want a new rule set.",
      session: "5 to 12 minutes",
      difficulty: "Medium",
      tags: ["merge", "triples", "board"],
      featured: false
    },
    {
      slug: "blendrix",
      title: "Blendrix",
      category: "2048 & Merge",
      sourceUrl: "https://gamea.azgame.io/blendrix/",
      playerUrl: buildAzEmbed("blendrix"),
      summary: "Blend matching pieces into cleaner combinations while protecting board space.",
      intro: "Blendrix helps round out the merge category with a softer visual hook and approachable decision-making. It is easy to position as a low-friction puzzle recommendation.",
      bestFor: "Players who like neat board management and steady merge loops.",
      session: "4 to 12 minutes",
      difficulty: "Easy to medium",
      tags: ["blend", "merge", "board"],
      featured: false
    },
    {
      slug: "tetris",
      title: "Tetris",
      category: "Blocks & Bricks",
      sourceUrl: "https://azgames.io/tetris",
      playerUrl: "https://azgames.io/tetris.embed",
      summary: "Rotate falling blocks and clear lines in the timeless stacking classic.",
      intro: "Tetris is essential anchor content for any puzzle catalog. It gives the site a high-recognition classic that supports both search visibility and direct play intent.",
      bestFor: "Players who want a familiar block puzzle with instant replay value.",
      session: "5 to 20 minutes",
      difficulty: "Medium",
      tags: ["tetris", "blocks", "classic"],
      featured: true
    },
    {
      slug: "bricky-blast",
      title: "Bricky Blast",
      category: "Blocks & Bricks",
      sourceUrl: "https://gamea.azgame.io/bricky-blast/",
      playerUrl: buildAzEmbed("bricky-blast"),
      summary: "Fit block shapes carefully and clear dense rows before the board closes in.",
      intro: "Bricky Blast is a strong support page for players who like modern block-clearing loops but want something lighter than a long Tetris session.",
      bestFor: "Fans of compact board clearing and shape placement.",
      session: "4 to 10 minutes",
      difficulty: "Easy to medium",
      tags: ["blocks", "rows", "placement"],
      featured: false
    },
    {
      slug: "bricky-break",
      title: "Bricky Break",
      category: "Blocks & Bricks",
      sourceUrl: "https://gamea.azgame.io/bricky-break/",
      playerUrl: buildAzEmbed("bricky-break"),
      summary: "Aim rebounds, break brick patterns, and use angles to clear the board efficiently.",
      intro: "Bricky Break adds a different pacing style to the block category. It is more about angle planning and shot economy than about line placement.",
      bestFor: "Players who like bounce physics and target clearing.",
      session: "4 to 10 minutes",
      difficulty: "Easy to medium",
      tags: ["bricks", "angles", "arcade"],
      featured: false
    },
    {
      slug: "tetrix-online",
      title: "Tetrix Online",
      category: "Blocks & Bricks",
      sourceUrl: "https://game.azgame.io/tetrix-online/",
      playerUrl: buildAzEmbed("tetrix-online"),
      summary: "A browser version of falling-block line clearing with quick restart loops.",
      intro: "Tetrix Online is useful alongside Tetris because some users search for branded-adjacent or alternate naming when looking for block stackers in browser.",
      bestFor: "Players who want fast line-clearing sessions without setup.",
      session: "5 to 15 minutes",
      difficulty: "Medium",
      tags: ["tetrix", "blocks", "lines"],
      featured: false
    },
    {
      slug: "block-slide",
      title: "Block Slide",
      category: "Blocks & Bricks",
      sourceUrl: "https://game.azgame.io/block-slide/",
      playerUrl: buildAzEmbed("block-slide"),
      summary: "Slide blocks into open lanes and solve each compact board arrangement.",
      intro: "Block Slide fits the pure logic side of the block category. It works especially well for users who prefer planning and movement constraints over speed.",
      bestFor: "Players who enjoy compact board logic puzzles.",
      session: "3 to 9 minutes",
      difficulty: "Medium",
      tags: ["slide", "blocks", "logic"],
      featured: false
    },
    {
      slug: "block-blast-3d",
      title: "Block Blast 3D",
      category: "Blocks & Bricks",
      sourceUrl: "https://game.azgame.io/block-blast-3d/",
      playerUrl: buildAzEmbed("block-blast-3d"),
      summary: "Place and clear 3D-styled blocks while planning a few moves ahead.",
      intro: "Block Blast 3D gives the block section a more visual, modern option. It can attract players who want familiar mechanics with a different surface feel.",
      bestFor: "Players who like block strategy with a slightly flashier presentation.",
      session: "4 to 12 minutes",
      difficulty: "Easy to medium",
      tags: ["3d", "blocks", "strategy"],
      featured: false
    },
    {
      slug: "meme-puzzle",
      title: "Meme Puzzle",
      category: "Blocks & Bricks",
      sourceUrl: "https://game.azgame.io/meme-puzzle/",
      playerUrl: buildAzEmbed("meme-puzzle"),
      summary: "Assemble visual fragments into completed meme pictures or scenes.",
      intro: "Meme Puzzle broadens the catalog beyond strict number and block mechanics. It is more image-driven, which helps add variety to the browsing experience.",
      bestFor: "Players who want lighter, image-led puzzle sessions.",
      session: "3 to 8 minutes",
      difficulty: "Easy",
      tags: ["visual", "meme", "assembly"],
      featured: false
    },
    {
      slug: "stickman-hook",
      title: "Stickman Hook",
      category: "Arcade Brain Games",
      sourceUrl: "https://azgames.io/stickman-hook",
      playerUrl: "https://azgames.io/stickman-hook.embed",
      summary: "Swing between anchor points and keep momentum through short obstacle runs.",
      intro: "Stickman Hook is more arcade than classic puzzle, but it fits well as a reflex-heavy break between slower brain games. It adds energy to the catalog.",
      bestFor: "Players who like timing, momentum, and quick retries.",
      session: "2 to 8 minutes",
      difficulty: "Easy to medium",
      tags: ["arcade", "timing", "swing"],
      featured: false
    },
    {
      slug: "wacky-nursery",
      title: "Wacky Nursery",
      category: "Arcade Brain Games",
      sourceUrl: "https://gamea.azgame.io/wacky-nursery/",
      playerUrl: buildAzEmbed("wacky-nursery"),
      summary: "Work through playful stages with a quirky nursery theme and quick objectives.",
      intro: "Wacky Nursery adds tonal variety and a lighter mood to the library. It is useful as a casual recommendation between more demanding logic pages.",
      bestFor: "Players who want quick, playful browser sessions.",
      session: "3 to 9 minutes",
      difficulty: "Easy",
      tags: ["casual", "quirky", "short"],
      featured: false
    },
    {
      slug: "stack-rush",
      title: "Stack Rush",
      category: "Arcade Brain Games",
      sourceUrl: "https://gamea.azgame.io/stack-rush/",
      playerUrl: buildAzEmbed("stack-rush"),
      summary: "Manage balance and timing while building a stack through compact levels.",
      intro: "Stack Rush is a strong lightweight entry because the mechanic is obvious at a glance. That makes it easy to promote in cards, sidebars, and internal links.",
      bestFor: "Players who want simple controls and instant retries.",
      session: "2 to 7 minutes",
      difficulty: "Easy",
      tags: ["stacking", "timing", "casual"],
      featured: false
    },
    {
      slug: "knock-balls",
      title: "Knock Balls",
      category: "Arcade Brain Games",
      sourceUrl: "https://azgames.io/knock-balls",
      playerUrl: "https://azgames.io/knock-balls.embed",
      summary: "Use limited shots to knock down structures as efficiently as possible.",
      intro: "Knock Balls works well as a physics puzzle-adjacent page. It has simple goals, readable stages, and enough accuracy pressure to stay engaging.",
      bestFor: "Players who like precision, destruction, and quick level loops.",
      session: "3 to 8 minutes",
      difficulty: "Easy to medium",
      tags: ["physics", "shots", "targets"],
      featured: false
    },
    {
      slug: "tunnel-ball",
      title: "Tunnel Ball",
      category: "Arcade Brain Games",
      sourceUrl: "https://gamea.azgame.io/tunnel-ball/",
      playerUrl: buildAzEmbed("tunnel-ball"),
      summary: "Guide a rolling ball through narrow lanes and timing-based tunnel hazards.",
      intro: "Tunnel Ball gives the site a slightly faster game loop without losing the short-session browser appeal. It is good supporting content for mobile players.",
      bestFor: "Players who enjoy focus, timing, and movement control.",
      session: "2 to 6 minutes",
      difficulty: "Medium",
      tags: ["ball", "timing", "movement"],
      featured: false
    },
    {
      slug: "loop-breakout",
      title: "Loop Breakout",
      category: "Arcade Brain Games",
      sourceUrl: "https://game.azgame.io/loop-breakout/",
      playerUrl: buildAzEmbed("loop-breakout"),
      summary: "Control breakout-style rebounds through looping obstacle layouts.",
      intro: "Loop Breakout adds angle control and spatial awareness to the faster side of the catalog. It is easier to understand than it is to master.",
      bestFor: "Players who like rebound puzzles and arcade loops.",
      session: "4 to 9 minutes",
      difficulty: "Medium",
      tags: ["breakout", "angles", "arcade"],
      featured: false
    },
    {
      slug: "jelly-hop",
      title: "Jelly Hop",
      category: "Arcade Brain Games",
      sourceUrl: "https://game.azgame.io/jelly-hop/",
      playerUrl: buildAzEmbed("jelly-hop"),
      summary: "Time each hop precisely to keep the jelly moving through compact stages.",
      intro: "Jelly Hop is another strong short-session title. It gives the library a simple control scheme with a clear fail-and-retry loop that suits mobile play.",
      bestFor: "Players who enjoy timing-based skill games.",
      session: "2 to 6 minutes",
      difficulty: "Easy to medium",
      tags: ["jelly", "hop", "timing"],
      featured: false
    },
    {
      slug: "blocky-rush",
      title: "Blocky Rush",
      category: "Arcade Brain Games",
      sourceUrl: "https://game.azgame.io/blocky-rush/",
      playerUrl: buildAzEmbed("blocky-rush"),
      summary: "Move quickly through blocky obstacle routes with a strong retry rhythm.",
      intro: "Blocky Rush helps the site avoid feeling too narrow. It is a useful crossover title for visitors who like puzzle-flavored browser games but still want motion and pace.",
      bestFor: "Players who want energetic, quick-reset gameplay.",
      session: "2 to 7 minutes",
      difficulty: "Easy to medium",
      tags: ["blocky", "rush", "arcade"],
      featured: false
    }
  ];

  window.PUZZLE_GAMES_DATA = games;
  window.PUZZLE_GAMES_INDEX = Object.fromEntries(
    games.map(function (game) {
      return [game.slug, game];
    })
  );
})();
